### ISSUE TITLE
Flat.io Classrooms Showing Singulars 

### ISSUE THREAD

**Issue by Reader8765** [FlatIO/api-client-js#32]
I wasn't sure how to post an issue for the website, so I put it here. Basically, when you have multiple students or assignments in a classroom it still displays as student or assignment.

![image](https://user-images.githubusercontent.com/20914635/49585580-bf68e500-f92c-11e8-8bfe-da8d2d725d08.png)

A minor bug, but still worth enhancing.

**Comment by gierschv** [comment]
Hi there,

Thanks a lot for your feedback. I added that issue on our internal bug tracker. This is an interface we will rework in Q1 2019, and we now display correct plurals in all our updates since late 2017, so this will be fixed at the same time :)

In the meantime, please feel free to send us an email at hello@flat.io for all issues or feedback regarding our product itself.

Thank you!
Vincent
